- .gitignore
- README.md
- bower.json
- gulpfile.js
- package.json
- src/Data/Proxy.purs
- src/Network/HTTP/Affjax.purs
- src/Network/HTTP/Affjax/Request.purs
- src/Network/HTTP/Affjax/Response.purs
- src/Network/HTTP/Affjax/ResponseType.purs
- src/Network/HTTP/Method.purs
- src/Network/HTTP/MimeType.purs
- src/Network/HTTP/MimeType/Common.purs
- src/Network/HTTP/RequestHeader.purs
- src/Network/HTTP/ResponseHeader.purs
- src/Network/HTTP/StatusCode.purs
- src/Type/Proxy.purs
- test/Main.purs
Resolves #1 (maybe!)
- The free monad is gone in favour of using `options`.
- We now have `Requestable` and `Responsable` classes to deal with conversions of values.
- The XHR `contentType` property is set based on the expected `Responsable` value.
- I still need to do some work with handling the "default" XHR response values as it's all very unsafe right now, I need to figure out a problem I'm having with `ArrayBuffers` being sent across not coming through with the right length.
- One disadvantage of this approach is now response values must be explicitly typed or used so they are unified with a type to prevent a `No instance for Responsable uXXXX` error.
- I need to make simple `get`, `post`, etc. combinators.
- We may still want a free monad type thing anyway, as with this `options` …
> `Options` based approach

- src/Network/HTTP/Affjax.purs
- test/Main.purs
Resolves #10 
It doesn't seem that there is much real information we can get when `onerror` occurs. I looked into using `status` or `statusText`, but they are `0` and `""` when `onerror` fires, as they are populated when a request completes successfully.
At least now the object returned actually is an `Error`, and has a somewhat meaningful message.
> Better handler for XHR onerror

- README.md
- bower.json
- src/Network/HTTP/Affjax.purs
- test/Main.purs
> Add cancellation support

- src/Network/HTTP/Affjax.purs
- src/Network/HTTP/Affjax/Response.purs
The previous fix for this was less than ideal, as using `JSONResponse` in custom `Respondable` instances resulted in it coming through as a string regardless. Here is a workaround to pre-process the response in the JSON case instead.
> Better fix for IE JSON responseType

- README.md
- trace -> log
- An Library -> A Library
Without this change, the example gives [this erroneous output](https://gist.github.com/aspidites/0f3a20695a2c70555712)
> Updated readme code to a working example.

- .travis.yml
- package.json
- src/Network/HTTP/Affjax.js
- test/Main.purs
Fixes #29. This passes all the tests in my other PR, but currently you have to set up an http server on port 80 to proxy to the test server to get them to work.
> node.js support, via npm package 'xmlhttprequest'

- package.json
- src/Network/HTTP/Affjax.js
This is a slightly sneaky trick to prevent webpack, etc. attempting to bundle node's `url` and `xmlhttprequest` modules in the JS when bundling for the browser.
> Use module.require to prevent bundling for browser

- src/Network/HTTP/Affjax.js
After bundling this `if` condition was becoming true in the browser too.
It definitely works this time, I `bower link`ed it into the slamdata build to test.
> Detect node with module.require

- bower.json
- docs/Network.HTTP.Affjax.md
- src/Network/HTTP/Affjax.purs
- test/Main.purs
This resolves #40.
This is a breaking API change, so an alternative would be to keep the old interface for compatibility, and add a new combinator, `retryWithPolicy`. What do folks think?
> [Retries] add RetryPolicy (#40)

- src/Network/HTTP/Affjax/Response.purs
Resolves #5
In the process of upgrading https://github.com/waterson/purescript-webaudio to compile under PureScript 0.7.x, and trying to get one of its tests to pass, I needed to have an instance of Respondable for ArrayBuffer available to me when issuing a get:
affjaxResponse <- get "/a_sound.wav" :: Aff ( ajax :: AJAX ) (AffjaxResponse ArrayBuffer)
Ultimately a call to decodeAudioData in JavaScript is made to play a sound, and indeed it needs an ArrayBuffer passed to it: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/decodeAudioData. I did try using an AffjaxResponse Blob, but that didn't work. I also tried just creating a local instance but PureScript disallows so-called "orphan instances".
If there is a better, less invasive way to accomplish this, let me know; I just …
> Addressed https://github.com/slamdata/purescript-affjax/issues/5

- .travis.yml
- README.md
- package.json
- src/Network/HTTP/Affjax.js
Fixes #44 by replacing use of the Node ```xmlhttprequest``` module with ```xhr2```.
This only affects those running purescript-affjax on Node, not in the browser. They will need to install the ```xhr2``` package as a local npm dependency instead of ```xmlhttprequest```.
This is therefore a breaking change for them. However, we could preserve backwards compatibility by adding an extra couple of lines to still use the ```xmlhttprequest``` package as a fallback if ```xhr2``` isn't found.
> Replace xmlhttprequest module with xhr2

- bower.json
- docs/Network.HTTP.Affjax.Request.md
- docs/Network.HTTP.Affjax.Response.md
- package.json
- src/Network/HTTP/Affjax.purs
- src/Network/HTTP/Affjax/Request.purs
- src/Network/HTTP/Affjax/Response.purs
What do you think of this @jdegoes?
Using a `Maybe MimeType` allows us to take advantage of the browser constructing the correct header for `FormData` and the like (generating a boundary, etc.) but allow us to specify our own in cases where the content is not a standard XHR thing, like JSON.
The `Accept` and `Content-Type` can still be specified manually in the request, and will take precedence over the values provided by the instances.
Resolves #8, resolves #6.
> Include mime types in Requestable/Respondable for setting headers

- src/Network/HTTP/Affjax.purs
- src/Network/HTTP/Affjax/Response.purs
- src/Network/HTTP/StatusCode.purs
Resolves #55 - @cdepillabout thanks, it wasn't changed intentionally, I'm not sure how it got lost
Resolves #54 - @teh the code you noticed went missing was replaced with this that also went missing at some point, I think this is a better fix as it will automatically apply the fix for any JSONResponse rather than having to handle it in every instance that expects it.
> Restore parse fix for JSON responses

- docs/Network.HTTP.Affjax.Request.md
- docs/Network.HTTP.Affjax.Response.md
- docs/Network.HTTP.Method.md
- docs/Network.HTTP.MimeType.md
- docs/Network.HTTP.RequestHeader.md
- docs/Network.HTTP.ResponseHeader.md
- docs/Network.HTTP.StatusCode.md
- package.json
- src/Network/HTTP/Affjax/Response.purs
- test/Main.purs
- upgrade `purescript`, `gulp-purescript` build dependencies
- fix warnings
This warrants just a patch version release, because the only dependencies changed are not part of the `bower` distribution.
> Update build, fix warnings

- src/Network/HTTP/Affjax.js
- src/Network/HTTP/Affjax.purs
Adds a [withCredentials](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials) field to `AffjaxRequest` and the internal `AjaxRequest`, that is subsequently set on the underlying `XMLHttpRequest`.
This enables the user to allow cookies, authorisation headers, and TLS certificates to be sent with cross site Access-Control requests. This flag also allows the user to control whether response cookies (via Set-Cookie) should be ignored by the user-agent.
In theory the `Set-Cookie` test that is [commented out](https://github.com/slamdata/purescript-affjax/blob/c1d346dddfe36b3f6cc72d0e418a6d20b69a2a6a/test/Main.purs#L116) should work with the following:
```
A.log "Testing CORS, HTTPS"
let cors = defaultRequest
{ url             = "https://cors-test.appspot.com/test"
, …
```
> Adding support for setting XMLHttpRequest.withCredentials

- bower.json
(Which fixes the FFI-related errors that 0.8.4 brings to light.)
> Bumps purescript-dom dependency to 0.2.20.

- src/Network/HTTP/Affjax.js
First, thanks for all your work on Purescript and its libraries.  I benefit greatly from your work.
I found and fixed a nasty bug this morning...
`xhr.getAllResponseHeaders()` returns the headers separated by CRLF, not just LF.
See [here](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/getAllResponseHeaders) and [here](https://www.w3.org/TR/XMLHttpRequest/#the-getallresponseheaders()-method). 
Presently, `purescript-affjax` splits only on `\n`.  See [here] (https://github.com/slamdata/purescript-affjax/blob/master/src/Network/HTTP/Affjax.js#L64).
Ordinarily, it wouldn't be a problem.  But when your workflow involves extracting an 'X-Auth-Token' from the header of an AJAX response, and then sending that token value as a header value of a new AJAX request, the new request …
> Fixed bug in splitting headers

- src/Network/HTTP/Affjax.js
Hello,
Ajax does not work in electron because there is a `module` object in the scope. This PR fixes the problem. 
To detect running in electron, I referred https://github.com/electron/electron/issues/2288.
> make it work for electron

- bower.json
- package.json
- src/Network/HTTP/Affjax.js
- src/Network/HTTP/Affjax.purs
- src/Network/HTTP/Affjax/Request.purs
- test/Main.purs
I've been working on updating some packages for PureScript 0.11. I've bumped the dependency versions, updated the syntax, and dealt with API changes in the dependencies. (Control.Monad.Aff.delay instead of later', removal of parseJSON from Data.Foreign, etc.) The only public-facing API change is changing Int to Milliseconds in RetryPolicy.
The syntax in the test has also been updated, but I was not able to successfully execute the test and I am not sure whether that is a local problem or something that needs to be fixed ...
Let me know if it looks good!
> Updates for PureScript 0.11

- bower.json
- package.json
- src/Network/HTTP/Affjax.purs
- src/Network/HTTP/Affjax/Request.purs
- src/Network/HTTP/Affjax/Response.purs
- src/Network/HTTP/ResponseHeader.purs
- src/Network/HTTP/StatusCode.purs
- test/Main.purs
There's a slight hitch in removing `Respondable`, as when the request is made, the `responseType` param needs setting, which has an effect on how the XHR interprets the response. Currently we can do this as we know the intended response before it arrives, but if we switch to a sum it's not obvious how to work with it.
ping @natefaubion
> Remove `Requestable` and `Respondable` classes

- README.md
- src/Affjax.purs
- test/DocExamples.purs
- test/Main.purs
The "options" part is kinda redundant, as it does fully describe a request. Especially now the `ResponseFormat` has also been included in the record, rather than as a separate argument to `request`.
> Rename RequestOptions to Request

- src/Affjax.purs
Apparently there has been some update recently and `Affjax.request` no longer takes `ResponseFormat` as the first parameter. Update docs to reflect that.
> Update doc comment for Affjax.request

- src/Affjax.js
I found a critical issue that deadlocking scripts.
For example, on client PC that placed on very unstable wireless network, Google Chrome rarely raises `net::ERR_TIMED_OUT` from xhr.
Now Affjax does not handle a timeout path, then script gets stuck eternally, a continuation will be discarded.
I think xhr timeout must be handled with error callback.
And sorry I didn't know how to reproduce this, but I confirmed that this patch fixed the title issue by actual environment.
---
purs 0.12.2
Google Chrome Version 72.0.3626.81 (Official Build) (64-bit)
purescript-affjax with purescript-halogen
> Fix the script got stuck when request timed out

- src/Affjax.js
xhr2 supports setting a base url globally on the prototype, using a static method.  I was trying to do this, so it was rather distressing to find Affjax overriding it with `localhost`:smile:
This PR makes `fixupUrl` detect whether the `xhr` object has a defined `nodejsBaseUrl`, and if so it just behaves the same way as in the browser version.  BTW the documentation comments say that this xhr2-only extension to the XHR API is "stable".
> On node.js don't override a base url already set in xhr2

- package.json
- src/Affjax.js
- src/Affjax.purs
Resolves #139
This will prevent potential problems arising when a too-new `purescript-form-urlencoded` is used.
> Type unsafe coercions

- README.md
- bower.json
- src/Affjax.purs
- test/DocExamples.purs
- test/Main.purs
Also cut down on the helper functions by just using `Maybe RequestBody.RequestBody`, and remove the retrying stuff that I doubt anybody uses.
> Update for fallible `FormURLEncoded`, don't use `Aff` error channel anymore

- src/Affjax/ResponseFormat.purs
As far as I can tell this is no longer used anywhere, see [here](https://github.com/slamdata/purescript-affjax/search?q=ResponseFormatError&unscoped_q=ResponseFormatError).
> Remove obsolete ResponseFormatError

- src/Affjax/StatusCode.purs
Makes it easier for users of the library to access the underlying
statuscode with `unwrap`.
> Add a Newtype instance to StatusCode

- src/Affjax.js
- src/Affjax.purs
- test/Main.js
- test/Main.purs
A simple timeout feature with Maybe field in Request. Test case included. Closes #143.
It was easier than I've thought.
> timeout setting for Request

- CHANGELOG.md
- src/Affjax.js
- src/Affjax.purs
- test/Main.purs
**Description of the change**
fixes https://github.com/purescript-contrib/purescript-affjax/issues/155
---
**Checklist:**
> throw timeout error not as `XHRError Exn.Error`, but as separate error

- .github/workflows/ci.yml
- .gitignore
- .tidyrc.json
- CHANGELOG.md
- src/Affjax.purs
- test/Main.purs
**Description of the change**
Introduces the [`purs-tidy`](https://github.com/natefaubion/purescript-tidy) formatter. This formatter is a lightly opinionated tool we use to maintain a consistent style in the contrib libraries.
We ordinarily restrict to tools provided by the `core` or `contrib` projects. This tool is not, but it was developed and is maintained by core team members, and because it's a formatter it can't block maintenance or release of this library even in the event something goes catastrophically wrong with it.
---
**Checklist:**
> Introduce purs-tidy formatter

- README.md
- src/Affjax.purs
**Description of the change**
Resolves https://github.com/purescript-contrib/purescript-affjax/pull/171#issuecomment-1105259382 Since this is another part of #171, I don't think this needs a changelog entry.
CC @thomashoneyman 
---
**Checklist:**
> Update readme in light of affjax driver changes
